project:
  - type: "REPOSITORY" # or "ORGANIZATION"
  - id: 1
  - columns:
    - todo:
      - index: 0
      - name: "To do"
    - doing:
      - index: 1
      - name: "In progress"
    - done:
      - index: 2
      - name: "Done"
