project:
  type: "REPOSITORY" # or "ORGANIZATION"
  number: 1
  new_issue_column:
    index: 0
    # name: "To do"
  new_pull_request_column:
    index: 1
    # name: "In progress"

changelog:
  # See https://github.com/mikz/probot-changelog for details

  # The filename of the CHANGELOG that needs to be updated in every PullRequest
  filename: CHANGELOG.md

  # (optional) when files matching these patterns are changed then disallow merging
  # until the CHANGELOG is updated.
  # If this pattern is not included then **all** Pull Requests require an edit to 
  # the CHANGELOG file
  include:
    - /^src\//
